"""
Author: Ludwing Perez: lp@t2mc.net
SEMILLA3 LLC
https://cuvex.io/
"""
CUVEX = 'Cuvex'
WELCOME_TITLE = 'Welcome to'
INTERNET_NOTICE = "Before begin, check that you are not connected to the internet or you won't be able to process your NFC card."
# VERIFICATION_NOTICE = "Don't forget to verify the md5 or sha256 checksum of this application with the published checksums. If they don't match, do not use the application."
VERIFICATION_NOTICE = "For security reasons, in case of any error or manually interruption of the process, the app will close."
OK = 'Ok'
OPEN_CARD_TITLE = 'Open your card'
OPEN_INSTRUCIONS = 'Open the file with the content of your NFC card generated by the Cuvex app'
SELECT_CARD_FILE = 'Select file'
BIN_FILES = 'Bin files'
CARD_INFO_TITLE = 'Card Info'
CARD_ALIAS = 'Alias: {}'
SIGNERS_PLURAL = 'Your card was signed by {} persons'
SIGNERS_SINGULAR = 'Your card was signed by one person'
REQUIRED_PASSWORD_PLURAL = '{} passwords are required'
REQUIRED_PASSWORD_SINGULAR = 'Only one password is required'
PROCEED = 'Proceed'
CARD_VERSION = 'Card version: {}'
INPUT_PASSWORD_TITLE = 'Input password'
INPUT_PASSWORD_PROMPT = 'Enter password number {} of {}:'
SHOW_CARD_CONTENT_INSTRUCTIONS = "You have 2 minutes to review your card's content. You may add one minute to the viewing time, up to 5 minutes max."
REMAINING_TIME = 'Remaining time: {:02d}:{:02d}'
EXTEND_TIME = 'Extend time'
FINALIZE_VIEWING = 'Finalize'
CARD_CONTENT_TITLE = "Review your card's content"
END_TIME = "Time's up for review your card's content. To see it again, start the process again."
RESTART = 'Go back'
CHECK_INTERNET_CONNECTION = 'Check internet connection'
INTERNET_CONN_MSG = 'For your own security, it is required to be offline to proceed with decryption.\nPlease disconnect from any network to continue.\nDo you want to continue?'
EMPTY_CARD_MSG = 'Your card is empty'
BAD_FORMAT_CARD_MSG = 'Your card does not comply with the required format'
UNKNOWN_ERROR_MSG = 'An unknown error occurred while processing the card'
VERSION_NOT_SUPPORTED_MSG = 'Card version {} not supported'
ERROR_TITLE = 'Error'
IMPOSSIBLE_PROCESS_CARD = 'It was not possible to process the card.'
WAIT_TO_TRY_AGAIN = 'You have to wait for {:02d}:{:02d} minutes to try again.'
FAILED_DECRYPTION_WAIT = "It wasn't possible to decrypt your card. Possibly one or more of the passwords are not correct.  You have to wait for 5 minutes to try again."
FAILED_DECRYPTION_RETRY = "It wasn't possible to decrypt your card. Possibly one or more of the passwords are not correct.  You still have {} attempts left."
FEWER_PASSWORD_THAN_REQUIRED = 'Fewer passwords were entered than required.'
CLOSE = 'Close'