"""
Author: Ludwing Perez: lp@t2mc.net
SEMILLA3 LLC
https://cuvex.io/
"""
PRIMARY_BUTTONS_BG_COLOR = '#3F3F51'
SECONDARY_BUTTONS_BG_COLOR = '#405CA0'
WINDOW_BACKGROUND_COLOR = '#EDEDED'
CLICKED_BUTTON_COLOR = '#9191A8'

STL_STYLES = 'STYLES'
IMG_MAIN_LOGO = 'IMG_MAIN_LOGO'
FRAME_WELCOME = 'fr_wlc'
FRW_TITLE = 'frw_title'
FRW_CONNECTION_WARN = 'frw_cw'
FRW_VERIFY_WARN = 'FRW_VRF'
FRW_BTN_OK = 'FRW_OK'
FRW_IMG_LOGO = 'FRW_LOGO'
FRW_VERSION_LBL = 'FRW_VER'
FRW_OK_BUTTON = 'FRW_OK'

FRAME_OPEN = 'FR_O'
FRO_TITLE = 'FRO_TTL'
FRO_INSTRUCTIONS = 'FRO_INS'
FRO_BTN = 'FRO_BTN'

FRAME_CARD_INFO = 'FR_CI'
FRCI_TITLE = 'FRCI_TTL'
FRCI_ALIAS = 'FRCI_ALIAS'
FRCI_SIGNERS = 'FRCI_SGNS'
FRCI_REQUIRED = 'FRCI_RQD'
FRCI_VERSION = 'FRCI_V'
FRCI_BTN = 'FRCI_PCD'
FRCI_BTN_RESTART = 'FRCI_BR'

FRAME_CARD_CONTENT = 'FR_CC'
FRCC_TITLE = 'FRCC_TTL'
FRCC_INSTRUCTIONS = 'FRCC_INST'
FRCC_TIME = 'FRCC_T'
FRCC_CONTENT = 'FRCC_C'
FRCC_BTN_ADD_TIME = 'FRCC_AT'
FRCC_BTN_FINALIZE = 'FRCC_F'
FRCC_FRM_CN = 'FRCC_FRCN'

FRAME_END = 'FR_E'
FRE_END_MSG = 'FRE_M'
FRE_OK_BUTTON = 'FRE_B'

STYLE_MAIN_TITLE = 'title.TLabel'
STYLE_ALL_FRAMES = 'all.TFrame'
TITLE_FONT = 'Helvetica 18 bold'
VERSION_FONT = 'Helvetica 10 bold'
TIME_REMAINING_FONT = 'Helvetica 16 bold italic'
CONTENT_FONT = 'Helvetica 12 bold italic'